### ISSUE TITLE
Default number of workers/threads

### ISSUE THREAD

**Issue by fgyanz** [SUSE/klp-build#18]
Hi team,

As part of our ongoing efforts of improving the user experience, I'd like to propose yet another change. The default number of workers is currently set to **4**, and it can be overwritten at runtime by using the `--workers` option. Most of the times I find myself forgetting to add said option to my command line, meaning that `klp-build` will run with just 4 threads, which most of the times is not enough. Killing the process and starting over again doesn't seem like the best option, since that could mess up the setup.

As I see it, perhaps we could get rid of  `--workers` option (hence simplifying the program) and run with all the threads available in the machine. This is very much a subjective impression, and maybe I'm just the only one suffering this "issue". So before creating any PR I wanted to check your thoughts on this matter, as I don't want to affect anyone's workflow.

Kind regards,
Fernando

**Comment by marcosps** [comment]
The number of workers changed overtime, mostly because klp-ccp consumes a lot of resources, making my 16Gb laptop sit forever sometimes. For clang-extract that might have worked, since it's much faster, besides consuming much less memory.

**Comment by fgyanz** [comment]
Aye, klp-ccp is indeed the main problem here. The extraction process with just 4 threads takes forever. For clarification, what I'm actually proposing is setting the number of workers to `$nproc` instead of 4. So, for a server of 20 cores, by default the number of workers would be of `20` instead of `4`. Now, this has downsides too. In a laptop that could mean eating all the resources...

Another solution could be adding a `workers` option in the configuration file for setting the default value.

**Comment by marcosps** [comment]
Makes sense. I believe that we could also have new sections on the config for ce and klp-ccp to specify the number of workers per tool. What do you think? Would you like to craft a patch to add this functionality?

**Comment by fgyanz** [comment]
Good idea! Sure, I'll have a patch ready asap :)

**Comment by fgyanz** [comment]
Hi,
I finally pushed a few commits covering this topic (see 8574ff52d58f1aff5c7186409d17426a7667bfd1 and e66f6816ff4f8ab04be620448af4069931306d13). I think it's simpler for now to have just one generic "workers" setting in the configuration file. We can reuse this value for all the code that need to be parallelized, and not make ccp/ce exclusive. Nevertheless, in the future we can revisit this topic as the configuration file keeps evolving.

Thanks,
Fernando
