### ISSUE TITLE
Create a package for klp-build to openSUSE

### ISSUE THREAD

**Issue by marcosps** [SUSE/klp-build#3]
That would be nice :)

**Comment by jubalh** [comment]
Package is available in [devel:tools](https://build.opensuse.org/package/show/devel:tools/klp-build) and [submitted](https://build.opensuse.org/request/show/1182471) to Factory.

**Comment by marcosps** [comment]
Thanks a lot @jubalh !

**Comment by jubalh** [comment]
klp-build is now available on Tumbleweed `zypper in clang-extract`.

**Comment by marcosps** [comment]
Thanks a lot @jubalh ! Closing as fixed!
